### ISSUE TITLE
HA Version 2022.8.0b1 - BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by MattDog06** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#11]
**Configuration:**
```
light:
  platform: rpi_gpio_pwm
  leds:
    - name: System Cooling Fan
      pin: 18
```

**Following error occurs, when I want to turn on/off or change brightness of the light:**
Logger: homeassistant.components.automation.system_fan_control
Source: custom_components/rpi_gpio_pwm/light.py:125
Integration: Automatisierung (documentation, issues)
First occurred: 03:06:56 (2772 occurrences)
Last logged: 08:15:30

System: Fan control: Choose at step 1: choice 2: Error executing script. Unexpected error for call_service at pos 1: [Errno 32] Broken pipe
System: Fan control: Error executing script. Unexpected error for choose at pos 1: [Errno 32] Broken pipe
While executing automation automation.system_fan_control
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 984, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/rpi_gpio_pwm/light.py", line 125, in turn_on
    self._led.value = _from_hass_brightness(self._brightness)
  File "/usr/local/lib/python3.10/site-packages/gpiozero/devices.py", line 132, in __setattr__
    return super(GPIOBase, self).__setattr__(name, value)
  File "/usr/local/lib/python3.10/site-packages/gpiozero/output_devices.py", line 448, in value
    self._write(value)
  File "/usr/local/lib/python3.10/site-packages/gpiozero/output_devices.py", line 435, in _write
    super(PWMOutputDevice, self)._write(value)
  File "/usr/local/lib/python3.10/site-packages/gpiozero/output_devices.py", line 96, in _write
    self.pin.state = self._value_to_state(value)
  File "/usr/local/lib/python3.10/site-packages/gpiozero/pins/__init__.py", line 285, in <lambda>
    lambda self, value: self._set_state(value),
  File "/usr/local/lib/python3.10/site-packages/gpiozero/pins/pigpio.py", line 244, in _set_state
    value = int(value * self.factory.connection.get_PWM_range(self.number))
  File "/usr/local/lib/python3.10/site-packages/pigpio.py", line 1543, in get_PWM_range
    return _u2i(_pigpio_command(self.sl, _PI_CMD_PRG, user_gpio, 0))
  File "/usr/local/lib/python3.10/site-packages/pigpio.py", line 1025, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by RedMeKool** [comment]
I updated to 2022.8 and all is working as intended. Do you still get this on the non beta version?

**Comment by MattDog06** [comment]
I am currencly on 2022.8.2 and I am still getting the same error.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/rpi_gpio_pwm/light.py:125
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:55:44 (1 occurrences)
Last logged: 13:55:44

[547141921872] [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 984, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/rpi_gpio_pwm/light.py", line 125, in turn_on
    self._led.value = _from_hass_brightness(self._brightness)
  File "/usr/local/lib/python3.10/site-packages/gpiozero/devices.py", line 132, in __setattr__
    return super(GPIOBase, self).__setattr__(name, value)
  File "/usr/local/lib/python3.10/site-packages/gpiozero/output_devices.py", line 448, in value
    self._write(value)
  File "/usr/local/lib/python3.10/site-packages/gpiozero/output_devices.py", line 435, in _write
    super(PWMOutputDevice, self)._write(value)
  File "/usr/local/lib/python3.10/site-packages/gpiozero/output_devices.py", line 96, in _write
    self.pin.state = self._value_to_state(value)
  File "/usr/local/lib/python3.10/site-packages/gpiozero/pins/__init__.py", line 285, in <lambda>
    lambda self, value: self._set_state(value),
  File "/usr/local/lib/python3.10/site-packages/gpiozero/pins/pigpio.py", line 244, in _set_state
    value = int(value * self.factory.connection.get_PWM_range(self.number))
  File "/usr/local/lib/python3.10/site-packages/pigpio.py", line 1543, in get_PWM_range
    return _u2i(_pigpio_command(self.sl, _PI_CMD_PRG, user_gpio, 0))
  File "/usr/local/lib/python3.10/site-packages/pigpio.py", line 1025, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by RedMeKool** [comment]
I’m not seeing any errors in my logs. Currently on 2022.8.5
