### ISSUE TITLE
*Error while setting up rpi_gpio_pwm platform for light

### ISSUE THREAD

**Issue by Bernard13090** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#17]
Hi,

My HA is 2023.7.2

I installed as expected in the read.me with Manual installation.

Setting up rpi_gpio_pwm in configuration.yaml

```
# add Bernard

switch:
  - platform: rpi_gpio
    switches:
      - port: 17
        name: "Fan Office"
        unique_id: "fan_office_switch_port_17"

sensor:
  - platform: command_line
    name: "X CPU Temp"
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1)  }}"
    scan_interval: 10


  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

light:
  - platform: rpi_gpio_pwm
    leds:
      - name: RPI Cooling Fan
        pin: 18
        
climate:
  - platform: generic_thermostat
    name: RPI Cooling Fan Controller
    unique_id: rpi_cooling_fan_controller
    heater: light.rpi_cooling_fan
    target_sensor: sensor.X_CPU_Temp
    min_temp: 30
    max_temp: 70
    ac_mode: true
    target_temp: 30
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    min_cycle_duration:
      seconds: 30
    keep_alive:
      minutes: 1
    initial_hvac_mode: "cool"
```

```
2023-07-26 14:34:25.382 ERROR (MainThread) [homeassistant.components.light] Error while setting up rpi_gpio_pwm platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha-rpi_gpio_pwm/light.py", line 70, in setup_platform
    opt_args["pin_factory"] = PiGPIOFactory(host=led_conf[CONF_HOST], port= led_conf[CONF_PORT])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gpiozero/pins/pigpio.py", line 101, in __init__
    raise IOError('failed to connect to %s:%s' % (host, port))
OSError: failed to connect to localhost:8888
```

Have you an idea to solve this issue.

BR

Bernard

**Comment by kloodhu** [comment]
same here

**Comment by potzkin** [comment]
same here,
ha 2023.10.1

```
Error while setting up rpi_gpio_pwm platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio_pwm/light.py", line 70, in setup_platform
    opt_args["pin_factory"] = PiGPIOFactory(host=led_conf[CONF_HOST], port= led_conf[CONF_PORT])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gpiozero/pins/pigpio.py", line 101, in __init__
    raise IOError('failed to connect to %s:%s' % (host, port))
OSError: failed to connect to localhost:8888
```

**Comment by tmek1244** [comment]
Try changing default port to 8123 (or at least that's the port I connect to home assistant http://192.168.0.228:8123)

**Comment by oerkel47** [comment]
Could have multiple reasons:
- remote GPIO disabled on the pi
- gpiod service not running
- if using a custom docker setup, try using networkmode host. (or read this https://www.howtogeek.com/devops/how-to-connect-to-localhost-within-a-docker-container/)
