### ISSUE TITLE
ModuleNotFoundError: No module named 'RPi' - Home Assistant Version 2022.06

### ISSUE THREAD

**Issue by MattDog06** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#2]
Logger: homeassistant.config
Source: custom_components/rpi_gpio_pwm/light.py:8
Integration: rpi_gpio_pwm
First occurred: 07:18:58 (1 occurrences)
Last logged: 07:18:58

Platform error: light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/rpi_gpio_pwm/light.py", line 8, in <module>
    from pwmled.driver.pca9685 import Pca9685Driver
  File "/usr/local/lib/python3.9/site-packages/pwmled/driver/pca9685.py", line 6, in <module>
    import board
  File "/usr/local/lib/python3.9/site-packages/board.py", line 62, in <module>
    from adafruit_blinka.board.raspberrypi.raspi_4b import *
  File "/usr/local/lib/python3.9/site-packages/adafruit_blinka/board/raspberrypi/raspi_4b.py", line 3, in <module>
    from adafruit_blinka.microcontroller.bcm2711 import pin
  File "/usr/local/lib/python3.9/site-packages/adafruit_blinka/microcontroller/bcm2711/pin.py", line 2, in <module>
    import RPi.GPIO as GPIO
ModuleNotFoundError: No module named 'RPi'

**Comment by RedMeKool** [comment]
Did you install required GPIO module in Home Assistant? This is a requirement for this integration to function

**Comment by mcza88** [comment]
Hi,

in my case, with 'pigpio' add-on is correctly installed and running untill upgrade to 2022.6.0.
After the upgrade all the gpio_pwm based automations stopped working and the error appeared.
The only way to  make the config.yaml file valid is to comment the block in which I'm using the 'rpi_gpio_pwm' platform.

**The error is 'Platform error light.rpi_gpio_pwm - No module named 'RPi''**

and the config block is:

_light:
  - platform: rpi_gpio_pwm
    leds:
      - name: "rpi_cooling_fan"
        driver: gpio
        pins: [18]
        type: simple_


**Reverting to 2022.5.5 seems to solve the problem.**


**Last Working Setup:**

Home Assistant Core 2022.5.5

Home Assistant Supervisor 2022.05.3

Home Assistant OS 8.1

Kernel version 5.15.32-v8

Agent version 1.2.1

**Comment by RedMeKool** [comment]
Yes, they removed the Raspberry Pi GPIO integration in version 2022.6.0 and the HACS version I know of does not work either: https://github.com/thecode/ha-rpi_gpio

**Comment by Matz88** [comment]
Same issue here, also tried to install the ha-rpi_gpio from HACS but it does not work as is. Is there the need for some specific setting for the gpio-pwm to work with ha-rpi_gpio?

**Comment by Matz88** [comment]
ha-rpi_gpio from HACS works but of course only in on/off mode, maybe is just the matter of using the same low level code and calls as the ha-rpi_gpio for HA-Raspberry-pi-GPIO-PWM to fix the issue?

**Comment by clemenstyp** [comment]
this should fix it: #3

**Comment by RedMeKool** [comment]
Awesome job man! I'm gonna try it and release a new version

**Comment by RedMeKool** [comment]
Yes, it's fixed! Thanks @clemenstyp

**Comment by mcza88** [comment]
> this should fix it: #3

Thank you @clemenstyp !! 
well done!
