### ISSUE TITLE
Platform error light.rpi_gpio_pwm - Integration 'rpi_gpio_pwm' not found

### ISSUE THREAD

**Issue by gerhard611** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#20]
I am very new and I thought I didd everything as described... may be not.

my log:

2023-11-18 17:18:48.318 ERROR (SyncWorker_2) [homeassistant.loader] Error loading integration: rpi_gpio_pwm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 867, in _resolve_integrations_from_root
    integration = Integration.resolve_from_root(hass, root_module, domain)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 573, in resolve_from_root
    integration = cls(
                  ^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 645, in __init__
    _LOGGER.info("Loaded %s from %s", self.domain, pkg_path)
                                      ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 660, in domain
    return self.manifest["domain"]
           ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'domain'

How can I fix that? Domain seems to be somewhere missing?

Thank you so much

**Comment by gerhard611** [comment]
It is a copy paste issue via windows sambashare.
It works if you first download and the copy it - don't use save as.
