### ISSUE TITLE
unique_id invalid on 2024.2.1 release

### ISSUE THREAD

**Issue by si458** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#33]
## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4862
Installed Version | 1.34.0
Stage | running
Available Repositories | 1389
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 57.3 GB
disk_used | 19.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), Mosquitto broker (6.4.0), WireGuard (0.10.2), Advanced SSH & Web Terminal (17.1.0), File editor (5.8.0), ESPHome (2023.12.9), Speedtest (1.5.0), Log Viewer (0.17.0), Zigbee2MQTT (1.35.3-1), Whisper (1.0.2), Piper (1.4.0), Portainer (2.19.4-3), Neolink (Dev) (0.0.1), HassOS I2C Configurator (0.13a), I2C OLED Display (1.0.5), pigpio (1.5.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 8
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 February 2024 at 23:51
-- | --
current_recorder_run | 11 February 2024 at 12:22
estimated_db_size | 336.21 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

2024-02-11 12:23:29.332 ERROR (MainThread) [homeassistant.components.light] Error while setting up rpi_gpio_pwm platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio_pwm/light.py", line 71, in setup_platform
    led = PwmSimpleLed(PWMLED(pin, **opt_args), led_conf[CONF_NAME], led_conf[CONF_UNIQUE_ID])
                                                                     ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'unique_id'

### Reproduction steps

1.update from 2022 version to 2024
```
light:
  - platform: rpi_gpio_pwm
    leds:
      - name: RPI Cooling Fan
        pin: 14
        frequency: 25000
```
...


### Debug logs

```text
2024-02-11 12:23:29.332 ERROR (MainThread) [homeassistant.components.light] Error while setting up rpi_gpio_pwm platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio_pwm/light.py", line 71, in setup_platform
    led = PwmSimpleLed(PWMLED(pin, **opt_args), led_conf[CONF_NAME], led_conf[CONF_UNIQUE_ID])
                                                                     ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'unique_id'
```


### Diagnostics dump

_No response_

**Comment by si458** [comment]
It's OK I answered my own question! 
The readme hac changed and u need a unique id now which I hadn't set!
Added one and works a treat now
